# -*- coding: utf-8 -*-
from __future__ import absolute_import

import json
import sys
import time
from multiprocessing import Process
from io import BytesIO

import pytest

import thriftpy2
from thriftpy2.http import make_server as make_http_server, \
    make_client as make_http_client
from thriftpy2.protocol import TApacheJSONProtocolFactory
from thriftpy2.rpc import make_server as make_rpc_server, \
    make_client as make_rpc_client
from thriftpy2.thrift import TProcessor, TType
from thriftpy2.transport import TMemoryBuffer
from thriftpy2.transport.base import TTransportBase, TTransportException
from thriftpy2.transport.buffered import TBufferedTransportFactory


def recursive_vars(obj):
    if isinstance(obj, str):
        return obj
    if isinstance(obj, bytes):
        return obj
    if isinstance(obj, (int, float, bool)):
        return obj
    if isinstance(obj, dict):
        return {k: recursive_vars(v) for k, v in obj.items()}
    if isinstance(obj, (list, set)):
        return [recursive_vars(v) for v in obj]
    if hasattr(obj, '__dict__'):
        return recursive_vars(vars(obj))


class ChunkedMemoryTransport(TTransportBase):
    def __init__(self, value, chunk_size):
        self._buffer = BytesIO(value)
        self._chunk_size = chunk_size

    def is_open(self):
        return True

    def open(self):
        pass

    def close(self):
        self._buffer.close()

    def _read(self, sz):
        return self._buffer.read(min(sz, self._chunk_size))

    def write(self, buf):
        self._buffer.write(buf)

    def flush(self):
        pass


def load_test_thrift(module_name="test_thrift"):
    return thriftpy2.load(
        "apache_json_test.thrift",
        module_name=module_name
    )


def make_request_bytes(test_thrift, obj, seqid=0):
    args = test_thrift.TestService.test_args(test=obj)
    buf = TMemoryBuffer()
    oprot = TApacheJSONProtocolFactory().get_protocol(buf)
    oprot.write_message_begin("test", 1, seqid)
    oprot.write_struct(args)
    return buf.getvalue()


def read_request_args(test_thrift, data, chunk_size=4096):
    trans = ChunkedMemoryTransport(data, chunk_size)
    iprot = TApacheJSONProtocolFactory().get_protocol(trans)
    assert iprot.read_message_begin() == ("test", 1, 0)
    args = iprot.read_struct(test_thrift.TestService.test_args())
    iprot.read_message_end()
    return args


def test_thrift_transport():
    test_thrift = load_test_thrift()
    Test = test_thrift.Test
    Foo = test_thrift.Foo
    test_object = Test(
        tbool=False,
        tbyte=16,
        tdouble=1.234567,
        tlong=123123123,
        tshort=123,
        tint=12345678,
        tstr="Testing String",
        tsetofints={1, 2, 3, 4, 5},
        tmap_of_int2str={
            1: "one",
            2: "two",
            3: "three"
        },
        tlist_of_strings=["how", "do", "i", "test", "this?"],
        tmap_of_str2foo={'first': Foo("first"), "2nd": Foo("baz")},
        tmap_of_str2foolist={
            'test': [Foo("test list entry")]
        },
        tmap_of_str2mapofstring2foo={
            "first": {
                "second": Foo("testing")
            }
        },
        tmap_of_str2stringlist={
            "words": ["dog", "cat", "pie"],
            "other": ["test", "foo", "bar", "baz", "quux"]
        },
        tfoo=Foo("test food"),
        tlist_of_foo=[Foo("1"), Foo("2"), Foo("3")],
        tlist_of_maps2int=[
            {"one": 1, "two": 2, "three": 3}
        ],
        tmap_of_int2foo={
            1: Foo("One"),
            2: Foo("Two"),
            5: Foo("Five")
        },
        tbinary=b"\x01\x0fabc123\x00\x02"
    )
    # A request generated by apache thrift that matches the above object
    request_data = b"""[1,"test",1,0,{"1":{"rec":{"1":{"tf":0},"2":{"i8":16},
    "3":{"i16":123},"4":{"i32":12345678},"5":{"i64":123123123},"6":
    {"dbl":1.234567},"7":{"str":"Testing String"},"8":{"lst":["str",5,
    "how","do","i","test","this?"]},"9":{"map":["i32","str",3,{"1":"one",
    "2":"two","3":"three"}]},"10":{"set":["i32",5,1,2,3,4,5]},
    "11":{"map":["str","rec",2,{"first":{"1":{"str":"first"}},"2nd":
    {"1":{"str":"baz"}}}]},"12":{"map":["str","lst",
    2,{"words":["str",3,"dog","cat","pie"],"other":["str",5,"test",
    "foo","bar","baz","quux"]}]},"13":{"map":["str",
    "map",1,{"first":["str","rec",1,{"second":{"1":{"str":"testing"}}}]}]},
    "14":{"lst":["rec",3,{"1":{"str":"1"}},
    {"1":{"str":"2"}},{"1":{"str":"3"}}]},"15":{"rec":{"1":{
    "str":"test food"}}},"16":{"lst":["map",1,["str","i32",
    3,{"one":1,"two":2,"three":3}]]},"17":{"map":["str","lst",1,{"test":
    ["rec",1,{"1":{"str":"test list entry"}}]}]},
    "18":{"map":["i32","rec",3,{"1":{"1":{"str":"One"}},"2":{"1":
    {"str":"Two"}},"5":{"1":{"str":"Five"}}}]},
    "19":{"str":"AQ9hYmMxMjMAAg=="}}}}]"""

    class Handler:
        @staticmethod
        def test(t):
            # t should match the object above
            expected_a = recursive_vars(t)
            expected_b = recursive_vars(test_object)

            if TType.STRING != TType.BINARY:
                assert expected_a == expected_b
            return t

    tp2_thrift_processor = TProcessor(test_thrift.TestService, Handler())
    tp2_factory = TApacheJSONProtocolFactory()
    iprot = tp2_factory.get_protocol(TMemoryBuffer(request_data))
    obuf = TMemoryBuffer()
    oprot = tp2_factory.get_protocol(obuf)

    tp2_thrift_processor.process(iprot, oprot)

    # output buffers should be the same
    final_data = obuf.getvalue()
    assert json.loads(request_data.decode('utf8'))[4]['1'] == \
           json.loads(final_data.decode('utf8'))[4]['0']


@pytest.mark.skipif(sys.platform == "win32", reason="this test requires fork")
@pytest.mark.parametrize('server_func', [(make_rpc_server, make_rpc_client),
                                         (make_http_server, make_http_client)])
def test_client(server_func):
    test_thrift = load_test_thrift()

    class Handler:
        @staticmethod
        def test(t):
            return t

    def run_server():
        server = make_http_server(
            test_thrift.TestService,
            handler=Handler(),
            host='localhost',
            port=9090,
            proto_factory=TApacheJSONProtocolFactory(),
            trans_factory=TBufferedTransportFactory()
        )
        server.serve()

    proc = Process(target=run_server, )
    proc.start()
    time.sleep(0.25)

    try:
        test_object = test_thrift.Test(
            tdouble=12.3456,
            tint=567,
            tstr='A test \'{["string',
            tmap_of_bool2str={True: "true string", False: "false string"},
            tmap_of_bool2int={True: 0, False: 1}
        )

        client = make_http_client(
            test_thrift.TestService,
            host='localhost',
            port=9090,
            proto_factory=TApacheJSONProtocolFactory(),
            trans_factory=TBufferedTransportFactory()
        )
        res = client.test(test_object)
        assert recursive_vars(res) == recursive_vars(test_object)
    finally:
        proc.terminate()
    time.sleep(1)


def test_load_data_handles_chunked_messages():
    test_thrift = load_test_thrift(module_name="chunked_messages_test_thrift")
    first = test_thrift.Test(
        tstr='你好 \\\\ "quoted" [brackets] 😀🚀🎉',
        tlist_of_strings=['["nested"]', 'slash\\\\quote\\"', '中文😀🎉'],
    )
    second = test_thrift.Test(tstr="第二条 😀🚀🎉")
    transport = ChunkedMemoryTransport(
        b" \n\t" + make_request_bytes(test_thrift, first) + make_request_bytes(test_thrift, second),
        chunk_size=7,
    )
    iprot = TApacheJSONProtocolFactory().get_protocol(transport)

    assert iprot.read_message_begin() == ("test", 1, 0)
    first_args = iprot.read_struct(test_thrift.TestService.test_args())
    iprot.read_message_end()

    assert iprot.read_message_begin() == ("test", 1, 0)
    second_args = iprot.read_struct(test_thrift.TestService.test_args())
    iprot.read_message_end()

    assert recursive_vars(first_args.test) == recursive_vars(first)
    assert recursive_vars(second_args.test) == recursive_vars(second)


def test_load_data_raises_eof_for_truncated_payload():
    test_thrift = load_test_thrift(module_name="truncated_test_thrift")
    request_data = make_request_bytes(test_thrift, test_thrift.Test(tstr="truncated"))[:-1]
    iprot = TApacheJSONProtocolFactory().get_protocol(
        ChunkedMemoryTransport(request_data, chunk_size=4)
    )

    with pytest.raises(TTransportException) as exc_info:
        iprot.read_message_begin()

    assert exc_info.value.type == TTransportException.END_OF_FILE
